name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        version: 9.4.0

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm i

    - name: Build
      run: pnpm build

    - name: Release
      run: |
        gh release upload release --clobber dist/osu-mpbd.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

